<!DOCTYPE html> 
<html lang="en"> 

<head> 
    <title>JS Error Constructor</title> 
</head> 

<body> 
    <script> /* Error */
        console.log("------------------>>> Error");

        let error = new Error("Test Error");
        throw error;

        // Output:
        // Uncaught Error: Test Error 
        //   at 49 - JS Error Constructor.html:12:21
    </script>

    <script> /* ReferenceError */
        console.log("------------------>>> ReferenceError");

        // An illegal reference has occurred.
        let errorRef = new ReferenceError("Test Reference Error");
        throw errorRef;
        
        // Output:
        // Uncaught ReferenceError: Test Reference Error
        //   at 49 - JS Error Constructor.html:24:24
    </script>

    <script> /* SyntaxError */
        console.log("------------------>>> SyntaxError");

        // A syntax error has occurred.
        let errorSyn = new SyntaxError("Test Syntax Error");
        throw errorSyn;
        
        // Output:
        // Uncaught SyntaxError: Test Syntax Error (at 49 - JS Error Constructor.html:36:24)
        //   at 49 - JS Error Constructor.html:36:24
    </script>

    <script> /* TypeError */
        console.log("------------------>>> TypeError");

        // A type error has occurred.
        let errorType = new TypeError("Test Type Error");
        throw errorType;

        // Output:
        // Uncaught TypeError: Test Type Error
        //   at 49 - JS Error Constructor.html:48:25
    </script>

    <script> /* RangeError */
        console.log("------------------>>> RangeError");

        // A number "out of range" has occurred.
        let errorRange = new RangeError("Test Range Error");
        throw errorRange;

        // Output:
        // Uncaught RangeError: Test Range Error
        //   at 49 - JS Error Constructor.html:60:26
    </script>

    <script> /* EvalError */
        console.log("------------------>>> EvalError");

        // An error has occurred in the eval() function.
        let errorEval = new EvalError("Test Eval Error");
        throw errorEval;

        // Output:
        // Uncaught EvalError: Test Eval Error
        //   at 49 - JS Error Constructor.html:72:25
    </script>

    <script> /* URIError */
        console.log("------------------>>> URIError");

        // An error in encodeURI() has occurred.
        let errorURI = new URIError("Test URI Error");
        throw errorURI;

        // Output:
        // Uncaught URIError: Test URI Error
        //   at 49 - JS Error Constructor.html:84:24
    </script>
</body> 

</html>